Repository The-Heeler-House/bot-bilby, pull requests merged in 2024-05, with the labels that each got.

#4 Better error logging
  src/Commands/index.ts
  src/Commands/text/add_character.ts
  src/Commands/text/remove_character.ts
  src/Commands/text/set_character.ts
  src/Commands/text/toggle_gate.ts
  src/Commands/text/toggle_paging.ts
  src/Events/events/mediaDeletion.ts
  src/Events/events/mediaDeletionViaEdit.ts
  src/Events/events/reactionTrackingAdd.ts
  src/Events/events/reactionTrackingRemove.ts
  src/Events/index.ts
  src/Services/Pager/index.ts
  src/Services/State/index.ts
  src/index.ts
Labels: enhancement

#5 Digitalocean workflow
  .github/workflows/build-deploy.yml
  README.md
  src/Commands/index.ts
  src/constants.ts
  src/index.ts
  testingIds.json
  tsconfig.json
Labels: bug, enhancement

#7 Fix tracked messages crash
  src/Events/events/linkedMessageAdd.ts
  src/Events/events/linkedMessageRemove.ts
Labels: bug

#14 Add a minimum and maximum time to muteme
  src/Commands/slash/muteme.ts
Labels: bug

#15 Save state changes
  src/Commands/text/toggle_gate.ts
  src/Commands/text/toggle_paging.ts
  src/Events/events/linkedMessageAdd.ts
  src/Events/events/linkedMessageRemove.ts
  src/Services/State/index.ts
Labels: bug
