Repository The-Heeler-House/bot-bilby, pull requests merged in 2024-06, with the labels that each got.

#26 Fix a bug where the bot wasn't able to mute
  src/Commands/slash/muteroulette.ts
Labels: bug

#25 Urgent fix for linked message
  src/Commands/index.ts
  src/Events/events/accountAgeGate.ts
  src/Events/events/linkedMessageAdd.ts
  src/Events/events/linkedMessageRemove.ts
  src/Events/events/mediaDeletion.ts
  src/Events/events/mediaDeletionViaEdit.ts
  src/Events/events/moderationPings.ts
  src/Events/events/reactionTrackingAdd.ts
  src/Events/events/reactionTrackingRemove.ts
  src/Events/index.ts
  src/Helper/EventsHelper.ts
Labels: bug, help wanted

#23 Quality of Life changes
  .vscode/settings.json
  src/Commands/constants.ts
  src/Commands/index.ts
  src/Commands/slash/8ball.ts
  src/Commands/slash/bingo.ts
  src/Commands/slash/changelog.ts
  src/Commands/slash/character.ts
  src/Commands/slash/fortune.ts
  src/Commands/slash/guess.ts
  src/Commands/slash/hangman.ts
  src/Commands/slash/muteme.ts
  src/Commands/slash/muteroulette.ts
  src/Commands/text/status.ts
  src/Events/events/accountAgeGate.ts
  src/Events/events/linkedMessageAdd.ts
  src/Events/events/linkedMessageRemove.ts
  src/Events/events/mediaDeletion.ts
  src/Events/events/mediaDeletionViaEdit.ts
  src/Events/events/moderationPings.ts
  src/Events/events/reactionTrackingAdd.ts
  src/Events/events/reactionTrackingRemove.ts
  src/Helper/EventsHelper.ts
Labels: enhancement

#35 Fix saving Maps + Add setting default state for new state values
  src/Services/State/index.ts
Labels: bug, enhancement

#37 Adds trigger functionality
  src/Commands/text/add_trigger.ts
  src/Commands/text/edit_trigger.ts
  src/Commands/text/edit_trigger_cooldown.ts
  src/Commands/text/get_trigger.ts
  src/Commands/text/list_triggers.ts
  src/Commands/text/remove_trigger.ts
  src/Commands/text/view_trigger.ts
  src/Events/events/triggerResponses.ts
  src/Helper/FlowHelper.ts
  src/Services/Database/index.ts
  src/Services/Database/models/triggers.ts
  src/constants.ts
  testingIds.json
Labels: enhancement
